# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'Pawpulace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pawpulace
  pod 'React', path: '../node_modules/react-native', 
  :subspecs => [
     'Core',
     'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  # Auth0 Lock
  pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
pod 'RSKImageCropper'
pod 'QBImagePickerController'

  target 'PawpulaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end




